[calendar.scriptsolution]
name = "Script-Solution"
path = "/home/hrniels/.config/vdirsyncer-test/calendar-scso/calendar~jt7D6iFxhujcnk_A7SJmbFq"

[calendar.scriptsolution_tasks]
name = "ScSo Tasks"
path = "/home/hrniels/.config/vdirsyncer-test/tasks-scso/tasks~h26VsoBEVm_nzi6FeDvGvES"

[calendar.bi]
name = "BI"
path = "/home/hrniels/.config/vdirsyncer-test/calendar-bi/calendar"

[calendar.holidays]
name = "Holidays"
path = "/home/hrniels/.config/vdirsyncer-test/calendar-holidays/iorbbNt57wxpN2K3"

[calendar.oschair]
name = "OS Chair"
path = "/home/hrniels/.config/vdirsyncer-test/calendar-oschair/osstaff_shared_by_adam"

[calendar.oslwl]
name = "OS LWL"
path = "/home/hrniels/.config/vdirsyncer-test/calendar-oslwl/-_shared_by_adam"
disabled = true
