[calendar.scriptsolution]
name = "Script-Solution"
path = "/home/hrniels/.config/vdirsyncer-test/calendar-scso/calendar~jt7D6iFxhujcnk_A7SJmbFq"

[calendar.scriptsolution_tasks]
name = "ScSo Tasks"
path = "/home/hrniels/.config/vdirsyncer-test/tasks-scso/tasks~h26VsoBEVm_nzi6FeDvGvES"

[calendar.bi]
name = "BI"
path = "/home/hrniels/.config/vdirsyncer-test/calendar-bi/calendar"

[calendar.holidays]
name = "Holidays"
path = "/home/hrniels/.config/vdirsyncer-test/calendar-holidays/iorbbNt57wxpN2K3"

[calendar.oschair]
name = "OS Chair"
path = "/home/hrniels/.config/vdirsyncer-test/calendar-oschair/osstaff_shared_by_adam"

[calendar.oslwl]
name = "OS LWL"
path = "/home/hrniels/.config/vdirsyncer-test/calendar-oslwl/-_shared_by_adam"
disabled = true

[calendar.oslws]
name = "OS Lehre WS"
path = "/home/hrniels/.config/vdirsyncer-test/calendar-oslws/lehre-ws_shared_by_d688b6f0-b6c0-1031-9c9d-3f576beecc46"
disabled = true

[calendar.oslss]
name = "OS Lehre SS"
path = "/home/hrniels/.config/vdirsyncer-test/calendar-oslss/lehre-ss_shared_by_d688b6f0-b6c0-1031-9c9d-3f576beecc46"
disabled = true

[calendar.ospr]
name = "OS Prüfung"
path = "/home/hrniels/.config/vdirsyncer-test/calendar-ospr/prüfungstermine_shared_by_mhaehnel"
disabled = true
