last_alarm_check = "2024-12-21T07:35:37.419785481"

[calendar.bi]
path = "/home/hrniels/.config/vdirsyncer-test/calendar-bi/calendar"
name = "BI"
disabled = false

[calendar.holidays]
path = "/home/hrniels/.config/vdirsyncer-test/calendar-holidays/iorbbNt57wxpN2K3"
name = "Holidays"
disabled = false

[calendar.oschair]
path = "/home/hrniels/.config/vdirsyncer-test/calendar-oschair/osstaff_shared_by_adam"
name = "OS Chair"
disabled = false

[calendar.oslss]
path = "/home/hrniels/.config/vdirsyncer-test/calendar-oslss/lehre-ss_shared_by_d688b6f0-b6c0-1031-9c9d-3f576beecc46"
name = "OS Lehre SS"
disabled = true

[calendar.oslwl]
path = "/home/hrniels/.config/vdirsyncer-test/calendar-oslwl/-_shared_by_adam"
name = "OS LWL"
disabled = true

[calendar.oslws]
path = "/home/hrniels/.config/vdirsyncer-test/calendar-oslws/lehre-ws_shared_by_d688b6f0-b6c0-1031-9c9d-3f576beecc46"
name = "OS Lehre WS"
disabled = true

[calendar.ospr]
path = "/home/hrniels/.config/vdirsyncer-test/calendar-ospr/prüfungstermine_shared_by_mhaehnel"
name = "OS Prüfung"
disabled = true

[calendar.scriptsolution]
path = "/home/hrniels/.config/vdirsyncer-test/calendar-scso/calendar~jt7D6iFxhujcnk_A7SJmbFq"
name = "Script-Solution"
disabled = false

[calendar.scriptsolution_tasks]
path = "/home/hrniels/.config/vdirsyncer-test/tasks-scso/tasks~h26VsoBEVm_nzi6FeDvGvES"
name = "ScSo Tasks"
disabled = false
