[calendar.bi]
path = "/home/hrniels/.config/vdirsyncer-test/calendar-bi/calendar"
name = "BI"
disabled = false
fgcolor = "#ffffff"
bgcolor = "#1d77c0"
types = ["Event", "Todo"]

[calendar.bi.email]
name = "Nils Asmussen"
address = "nils.asmussen@barkhauseninstitut.org"

[calendar.bi.syncer.VDirSyncer]
cmd = ["/home/hrniels/Projects/eventix/tools/sync.sh", "calendar_bi"]
local_name = "calendar_bi_local"

[calendar.oslwl]
path = "/home/hrniels/.config/vdirsyncer-test/calendar-oslwl/-_shared_by_adam"
name = "OS LWL"
disabled = true
fgcolor = "#000000"
bgcolor = "#e1c4a8"
types = ["Event"]

[calendar.oslwl.email]
name = "Nils Asmussen"
address = "nils@os.inf.tu-dresden.de"

[calendar.oslwl.syncer.VDirSyncer]
cmd = ["/home/hrniels/Projects/eventix/tools/sync.sh", "calendar_oslwl"]
local_name = "calendar_oslwl_local"

[calendar.scriptsolution]
path = "/home/hrniels/.config/vdirsyncer-test/calendar-scso/calendar~jt7D6iFxhujcnk_A7SJmbFq"
name = "Script-Solution"
disabled = false
fgcolor = "#ffffff"
bgcolor = "#2ec17d"
types = ["Event"]

[calendar.scriptsolution.email]
name = "Nils Asmussen"
address = "nils@script-solution.de"

[calendar.scriptsolution.syncer.VDirSyncer]
cmd = ["/home/hrniels/Projects/eventix/tools/sync.sh", "calendar_scso"]
local_name = "calendar_scso_local"

[calendar.scriptsolution_tasks]
path = "/home/hrniels/.config/vdirsyncer-test/tasks"
name = "ScSo Tasks"
disabled = false
fgcolor = "#ffffff"
bgcolor = "#128421"
types = ["Todo"]
syncer = "FileSystem"

[calendar.test]
path = "/home/hrniels/.config/vdirsyncer-test/calendar-test/calendar~xTVGWlaUtoYnj4TOSK7v-ZV"
name = "Test"
disabled = false
fgcolor = "#ffffff"
bgcolor = "#00a915"
types = ["Event"]

[calendar.test.email]
name = "Nils Asmussen"
address = "nils@script-solution.de"

[calendar.test.syncer.VDirSyncer]
cmd = ["/home/hrniels/Projects/eventix/tools/sync.sh", "calendar_test"]
local_name = "calendar_test_local"
