[Icon Theme]
Name=Hicolor
Comment=Default fallback theme
Example=folder

Directories=256x256/scalable/apps 128x128/apps 64x64/apps 48x48/apps 32x32/apps

[256x256/scalable/apps]
Size=256
Context=Apps
Type=Fixed

[128x128/apps]
Size=128
Context=Apps
Type=Fixed

[64x64/apps]
Size=64
Context=Apps
Type=Fixed

[48x48/apps]
Size=48
Context=Apps
Type=Fixed

[32x32/apps]
Size=32
Context=Apps
Type=Fixed

[256x256/scalable/apps]
Size=256
Context=Apps
Type=Scalable
MinSize=1
MaxSize=512
